from app.models.crm import (
    User, UserRole,
    Lead, LeadSource, LeadStatus,
    CustomerRequirement,
    Vehicle, VehicleCategory, VehicleStatus,
    Quotation,
    TestDrive, TestDriveStatus,
    ExchangeVehicle,
    Booking, BookingStatus,
    FinanceApplication, FinanceStatus,
    InsurancePolicy,
    AccessoryItem, AccessoriesOrder,
    Invoice, Payment, PaymentMode,
    PDIRecord, PDIStatus,
    Delivery, DeliveryStatus,
    FollowUp, FollowUpType, FollowUpStatus,
    CallLog,
    Document,
    AuditLog,
    Notification,
)
